load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "iree-runtime",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "iree_runtime",
    edition = "2024",
    aliases = aliases(),
    data = ["//bazel/iree:tools"],
    deps = all_crate_deps(normal = True),
    visibility = ["//visibility:public"],
)

rust_test(
    name = "iree-runtime_tests",
    crate = ":iree-runtime",
    data = ["//bazel/iree:tools"],
    deps = all_crate_deps(normal_dev = True),
)
